### ISSUE TITLE
Non-canonical paths don't work when loading javascript library

### ISSUE THREAD

**Issue by piever** [JuliaGizmos/AssetRegistry.jl#7]
Javascript libraries are not found if I use a non-absolute path, for example in InteractBase the library
`const font_awesome = joinpath(@__DIR__, "..", "assets", "all.js")` is not found in Blink, see screenshot by @pfitzseb who reported the problem:

![screenshot](https://user-images.githubusercontent.com/6333339/45367060-44678b00-b5d8-11e8-8c05-e8bd2a67cc77.png)

**Comment by shashi** [comment]
I thought we did abspath and that normalizes paths...

**Comment by pfitzseb** [comment]
No, that's `normpath`. Neither of those take care of `~` though, so I added an `expanduser` as well...
